config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	get '/top' => 'homes#top'

	post '/posts' => 'posts#create'
	post '/posts/index' => 'posts#create'
	get '/posts/index' => 'posts#index'
	get '/posts/:id' => 'posts#show', as: 'post'
	get '/' => 'homes#top'
	get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
	patch '/posts/:id' => 'posts#update', as: 'update_post'
	delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	attachment :image
	validates :title, presence: true,
    length: { minimum: 1, maximum: 20 }
	validates :weather, presence: true,
    length: { minimum: 1, maximum: 10 }
	validates :body, presence: true,
    length: { minimum: 1, maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		
	end
	def new
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
  	# ストロングパラメーターを使用
    post = Post.new(post_params)
    # DBへ保存する
    post.save
    # トップ画面へリダイレクト
    redirect_to '/posts/index'
  end

  def index
  	@post = Post.new
  	@all = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
  	@post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to "/posts/index"
  end

  private
    def post_params
        params.require(:post).permit(:title, :body, :weather, :time, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb

<div id="top">
	<h1>Morimoto Kazuhiro</h1>
</div>
<div id="box">
	<%= image_tag("/assets/profile.png", :size=>"400x400", :id => "profile")  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MorimotoDiary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <h4>天気</h4>
    <%= f.text_field :weather %>
    <%= f.submit '保存' %>
<% end %>
<%=link_to "投稿一覧", "/posts/index" %>

app/views/posts/index.html.erb
<!--  <% @all.each do |post| %>
    <p>タイトル</p>
    <span>
        <%=link_to post.title, "/posts/#{post.id}" %>
    </span>
 <% end %>

 -->
<div class="container-fluid">
	<div class="row">
		<div class="col-md-4">
			<%= form_for(@post) do |f| %>
			<h4>タイトル</h4>
			<%= f.text_field :title %>

			<h4>本文</h4>
			<%= f.text_area :body %>

			<h4>天気</h4>
			<%= f.text_field :weather %>

			<h4>画像</h4>
			<%= f.attachment_field :image %>

			<h4><%= f.submit '投稿' %></h4>
			<% end %>
		</div>
		<div class="col-md-8">
			<table class="table">
				<thead>
					<tr>
						<th>タイトル</th>
						<th>天気</th>
						<th>本文</th>
						<th>投稿時間</th>
						<th>画像</th>
					</tr>
				</thead>
				<tbody>
					<% @all.each do |post| %>
						<tr>
							<th><%=link_to post.title, "/posts/#{post.id}" %></th>
							<td><%= post.weather %></td>
							<td><%= post.body %></td>
							<td><%= post.created_at.strftime('%Y/%m/%d %H:%M') %></td>
							<td>
								<% if post.image.nil? %>
		    					<%= link_to image_tag("/assets/no_data.png", :size=>"100x100") ,post_path(post.id) %>
					    		<% else %>
					    		<%=link_to (attachment_image_tag post, :image, :fill, 100, 100, format: 'jpeg') ,post_path(post.id) %>
					    		<% end %>
							</td>

						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>








app/views/posts/new.html.erb
<div id="top">
	<h3>新規投稿</h3>
</div>

<div id="box">
	<!-- form_for部分 -->
	<%= form_for(@post) do |f| %>

	    <h4>タイトル</h4>
	    <%= f.text_field :title %>

	    <h4>本文</h4>
	    <%= f.text_area :body %>

	    <h4>天気</h4>
	    <%= f.text_field :weather %>

	    <h4>画像</h4>
		<%= f.attachment_field :image %>

	    <h4><%= f.submit '投稿' %></h4>

	    <span><%=link_to "投稿一覧", "/posts/index" %></span>

	<% end %>
</div>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>
<h2>天気</h2>
<p><%= @post.weather %></p>
<h2>投稿時刻</h2>
<p><%= @post.created_at.strftime('%Y/%m/%d %H:%M') %></p>
<h2>画像</h2>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %>
<span><%=link_to "投稿一覧", "/posts/index" %></span>
<%= link_to "編集", edit_post_path(@post.id) %>
<%= link_to "削除", destroy_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>